sudo: required

language: c

compiler: 
  - gcc
  - clang

arch: 
  - amd64

branches:
  only:
    - master 

script:
  - make
  - ./icapp ZIPF
  - ./icbench -eBENCH -a1.2 -m0 -M255 -n100M ZIPF
  - ./icbench -eBITPACK/VBYTE -a1.2 -m0 -M255 -n100M ZIPF

matrix:
  include:
    - name: Linux arm
      os: linux
      arch: arm64
      compiler: gcc
 
    - name: Linux amd64
      os: linux

    - name: Windows-MinGW
      os: windows
      script: 
        - mingw32-make
        - ./icapp ZIPF

    - name: macOS, xcode11
      os: osx
      osx_image: xcode11

    - name: macOS, xcode9.4
      os: osx
      osx_image: xcode9.4

    - name: Power ppc64le
      os: linux-ppc64le
      compiler: gcc     

- addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
        - libtbb-dev
    env:
    - CC=gcc-8 CXX=g++-8
    - CXXFLAGS="-fuse-ld=gold"
cache: apt
addons:
  apt:
    packages:
    - libtbb-dev

