language: c

compiler: 
  - gcc
  - clang

arch:
  - arm64
  - amd64

branches:
  only:
    - master 

script:
  - make
  - ./icapp ZIPF
  - ./icbench -eBENCH -a1.2 -m0 -M255 -n100M ZIPF
  - ./icbench -eBITPACK/VBYTE -a1.2 -m0 -M255 -n100M ZIPF

matrix:
  include:
    - name: Linux
      os: linux

    - name: macOS, xcode11
      os: osx
      osx_image: xcode11
      script:
        - make

    - name: macOS, xcode9.4
      os: osx
      osx_image: xcode9.4
      script:
        - make

    - name: macOS, xcode7.3
      os: osx
      osx_image: xcode7.3
      script:
        - make

    - name: Windows, MinGW
      os: windows
      script:
        - make
