language: c

compiler: 
  - gcc
  - clang

arch:
  - amd64

branches:
  only:
    - master 

script:
  - make
  - ./icapp ZIPF
  - ./icbench -eBENCH -a1.2 -m0 -M255 -n100M ZIPF
  - ./icbench -eBITPACK/VBYTE -a1.2 -m0 -M255 -n100M ZIPF

matrix:
  include:
    - name: Linux arm
      os: linux
      arch: arm64
      compiler: gcc
 
    - name: Linux amd64
      os: linux

    - name: Power ppc64le
      os: linux-ppc64le
       
    - name: Windows-MinGW
      os: windows
      script: 
        - mingw32-make
        - ./icapp ZIPF

    - name: macOS, xcode11
      os: osx
      osx_image: xcode11

    - name: macOS, xcode9.4
      os: osx
      osx_image: xcode9.4

