language: c

arch:
  - amd64
# - arm64
# - s390x
# - ppc64le (gcc > 8.0)

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - cat /proc/cpuinfo
  - ./icapp ZIPF
  
matrix:
  include:
    - name: linux-arm64-gcc
      os: linux
      arch: arm64
      compiler: gcc

    - name: windows-mingw-w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
        - ./icapp ZIPF

    - name: apple-macOS-xcode
      os: osx
      script:
        - make
        - ./icapp ZIPF

    - name: linux-ppc64le-gcc-9
      os: linux
      arch: ppc64le
      env: CC=gcc-9
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-9

