sudo: required

language: c

arch: 
  - ppc64

branches:
  only:
    - master 

script:
  - make
  - ./icapp ZIPF

matrix:
  include:
    - name: Power ppc64le
      os: linux-ppc64le
      compiler: gcc     

- addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
        - libtbb-dev
    env:
    - CC=gcc-8 CXX=g++-8
    - CXXFLAGS="-fuse-ld=gold"
cache: apt
addons:
  apt:
    packages:
    - libtbb-dev

